In [121]:
import numpy as np
#np.random.seed(42)

n = 1000
d = 10
active_row = .1
active_col = .2

active_row_bool = np.random.rand(n) < active_row
active_col_bool = np.random.rand(n) < active_col
active_all_bool = np.logical_or(active_row_bool, active_col_bool)

active_row_indx = np.argwhere(active_row_bool).flatten()
active_col_indx = np.argwhere(active_col_bool).flatten()
active_all_indx = np.argwhere(active_all_bool).flatten()

active_row_indx.size, active_col_indx.size, active_all_indx.size


#X
#Y

#T
#N

#G

(107, 195, 276)

In [44]:
A = np.random.rand(9) < .1
B = np.random.rand(9) < .2
C = np.logical_or(A, B)
print(A)
print(B)
print(C)


[False False False False  True False False  True  True]
[ True False False False False False False  True False]
[ True False False False  True False False  True  True]


In [13]:
d = 8 #4096

W = np.random.randn(d, d)
W = ((W) * 10).astype(int) / 10
W = W @ W.T
W /= np.linalg.norm(W)

w = np.diag(W)

G = np.random.randn(d, d)
G = ((G) * 10).astype(int) / 10
G = G @ G.T
G /= np.linalg.norm(G)

In [14]:
# linear transform - 2-norm - full matrix - loss

L1 = .5 * np.trace(W.T @ W)
L2 = .5 * np.sum(np.square(W))
L3 = .5 * np.square(np.linalg.norm(W))
L4 = .5 * np.dot(W.ravel(), W.ravel())
L5 = .5 * np.tensordot(W, W)
print(np.array([L1, L2, L3, L4, L5]).reshape((-1, 1)))

%timeit L1 = .5 * np.trace(W.T @ W)
%timeit L2 = .5 * np.sum(np.square(W))
%timeit L3 = .5 * np.square(np.linalg.norm(W)) # <- about the same
%timeit L4 = .5 * np.dot(W.ravel(), W.ravel()) # <- fastest
%timeit L5 = .5 * np.tensordot(W, W)           # <- about the same

[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]
4.47 µs ± 61.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.56 µs ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.76 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.02 µs ± 8.47 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
11.7 µs ± 23.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
# linear transform - 2-norm - full matrix - gradient

%timeit D = W

19.8 ns ± 0.167 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [16]:
# linear transform - 2-norm - diagonal - loss

L1 = .5 * np.sum(np.square(w))
L2 = .5 * np.square(np.linalg.norm(w))
L3 = .5 * np.dot(w, w)
L4 = .5 * np.tensordot(w, w, 1)
print(np.array([L1, L2, L3, L4]).reshape((-1, 1)))

%timeit L1 = .5 * np.sum(np.square(w))
%timeit L2 = .5 * np.square(np.linalg.norm(w))
%timeit L3 = .5 * np.dot(w, w)                  # <- fastest
%timeit L4 = .5 * np.tensordot(w, w, 1)


[[0.25528348]
 [0.25528348]
 [0.25528348]
 [0.25528348]]
3.28 µs ± 24.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.31 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
863 ns ± 5.39 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
11.3 µs ± 26.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
# linear transform - 2-norm - diagonal - gradient

%timeit D = w

19.8 ns ± 0.181 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [18]:
# linear transform - 1-norm - full matrix - loss

L1 = np.sum(np.abs(W))
L2 = np.linalg.norm(W.ravel(), 1)
print(np.array([L1, L2]).reshape((-1, 1)))

%timeit L1 = np.sum(np.abs(W))            # <- same speed, more concise
%timeit L2 = np.linalg.norm(W.ravel(), 1)

[[6.11387974]
 [6.11387974]]
3.11 µs ± 25.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.77 µs ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
# linear transform - 1-norm - full matrix - gradient

%timeit D = np.sign(W)

274 ns ± 1.33 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
# linear transform - 1-norm - diagonal - loss

L1 = np.sum(np.abs(w))
L2 = np.linalg.norm(w, 1)
print(np.array([L1, L2]).reshape((-1, 1)))

%timeit L1 = np.sum(np.abs(w))    # <- same speed, more concise
%timeit L2 = np.linalg.norm(w, 1) 

[[1.96247498]
 [1.96247498]]
2.82 µs ± 33.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.68 µs ± 44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
# linear transform - 1-norm - diagonal - gradient

%timeit D = np.sign(w)

234 ns ± 2.99 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
# nonlinear transform - 2-norm - full matrix - loss

L1 = .5 * np.trace(W @ G @ W @ G)
A = W @ G; L2 = .5 * np.dot(A.ravel(), A.ravel('F'))
A = W @ G; L3 = .5 * np.dot(A.ravel(), A.T.ravel())
A = W @ G; L4 = .5 * np.tensordot(A, A.T)
L5 = .5 * np.dot((W @ G).ravel(), (W @ G).ravel('F'))
L6 = .5 * np.dot((W @ G).ravel(), (W @ G).T.ravel())
L7 = .5 * np.tensordot((W @ G), (W @ G).T)
L8 = .5 * np.dot((W @ G).ravel(), (G @ W).ravel())
L9 = .5 * np.tensordot((W @ G), (G @ W))
print(np.array([L1, L2, L3, L4, L5, L6, L7, L8, L9]).reshape((-1, 1)))

%timeit L1 = .5 * np.trace(W @ G @ W @ G)
%timeit A = W @ G; L2 = .5 * np.dot(A.ravel(), A.ravel('F')) 
%timeit A = W @ G; L3 = .5 * np.dot(A.ravel(), A.T.ravel())  # <- fastest
%timeit A = W @ G; L4 = .5 * np.tensordot(A, A.T)            
%timeit L5 = .5 * np.dot((W @ G).ravel(), (W @ G).ravel('F'))
%timeit L6 = .5 * np.dot((W @ G).ravel(), (W @ G).T.ravel())
%timeit L7 = .5 * np.tensordot((W @ G), (W @ G).T)
%timeit L8 = .5 * np.dot((W @ G).ravel(), (G @ W).ravel())
%timeit L9 = .5 * np.tensordot((W @ G), (G @ W))             # <- slower, no assignment

[[0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]
 [0.03401764]]
6.77 µs ± 71.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.38 µs ± 34.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.37 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
15.5 µs ± 99.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.71 µs ± 28.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.79 µs ± 35.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
16.7 µs ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.09 µs ± 27.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
15.9 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
# nonlinear transform - 2-norm - full matrix - gradient

%timeit D = G @ W @ G

2.36 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
# nonlinear transform - 2-norm - diagonal - loss

L1 = .5 * np.trace(np.diag(w) @ G @ np.diag(w) @ G)
A = w * G; L2 = .5 * np.dot(A.ravel(), A.ravel('F'))
A = w * G; L3 = .5 * np.dot(A.ravel(), A.T.ravel())
A = w * G; L4 = .5 * np.tensordot(A, A.T)
L5 = .5 * np.tensordot(w * G, w[:, None] * G)
L6 = .5 * np.dot((w * G).ravel(), (w * G).T.ravel())
L7 = .5 * np.sum(np.outer(w, w) * np.square(G))
L8 = .5 * np.sum(w * np.square(G) * w[:, None])
L9 = .5 * np.tensordot(np.outer(w, w), np.square(G))
L10 = .5 * np.dot(np.outer(w, w).ravel(), np.square(G).ravel())
print(np.array([L1, L2, L3, L4, L5, L6, L7, L8, L9, L10]).reshape((-1, 1)))

%timeit L1 = .5 * np.trace(np.diag(w) @ G @ np.diag(w) @ G)
%timeit A = w * G; L2 = .5 * np.dot(A.ravel(), A.ravel('F'))
%timeit A = w * G; L3 = .5 * np.dot(A.ravel(), A.T.ravel())
%timeit A = w * G; L4 = .5 * np.tensordot(A, A.T)
%timeit L5 = .5 * np.tensordot(w * G, w[:, None] * G)
%timeit L6 = .5 * np.dot((w * G).ravel(), (w * G).T.ravel())
%timeit L7 = .5 * np.sum(np.outer(w, w) * np.square(G))
%timeit L8 = .5 * np.sum(w * np.square(G) * w[:, None])
%timeit L9 = .5 * np.tensordot(np.outer(w, w), np.square(G))            # <- about the same
%timeit L10 = .5 * np.dot(np.outer(w, w).ravel(), np.square(G).ravel()) # <- fastest

[[0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]
 [0.02840476]]
10.9 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.89 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.89 µs ± 25.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
13.9 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.9 µs ± 43.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.96 µs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.09 µs ± 87.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.94 µs ± 65.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
16.2 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
4.71 µs ± 45.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
# nonlinear transform - 2-norm - diagonal - gradient

D1 = np.diag(G @ np.diag(w) @ G)
D2 = np.square(G) @ w
print(np.stack((D1, D2)))

%timeit D1 = np.diag(G @ np.diag(w) @ G)
%timeit D2 = np.square(G) @ w            # <- fastest

[[0.02027539 0.07847786 0.01266886 0.01221752 0.00599783 0.01748913
  0.03806123 0.04939317]
 [0.02027539 0.07847786 0.01266886 0.01221752 0.00599783 0.01748913
  0.03806123 0.04939317]]
6.26 µs ± 62.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.47 µs ± 6.08 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [26]:
# nonlinear transform - 1-norm - full matrix - loss

L1 = np.sum(np.abs(G @ W @ G))
L2 = np.linalg.norm((G @ W @ G).ravel(), 1)
print(np.array([L1, L2]).reshape((-1, 1)))

%timeit L1 = np.sum(np.abs(G @ W @ G))              # <- more concise
%timeit L2 = np.linalg.norm((G @ W @ G).ravel(), 1) # <- faster

[[0.70512853]
 [0.70512853]]
6.49 µs ± 41.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
6.34 µs ± 56.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
# nonlinear transform - 1-norm - full matrix - gradient

%timeit D = G @ np.sign(G @ W @ G) @ G

5.02 µs ± 46.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
# nonlinear transform - 1-norm - diagonal - loss

L1 = np.sum(np.abs(G @ np.diag(w) @ G))
L2 = np.sum(np.abs((w * G) @ G))
L3 = np.linalg.norm(((w * G) @ G).ravel(), 1)
print(np.array([L1, L2, L3]).reshape((-1, 1)))

%timeit L1 = np.sum(np.abs(G @ np.diag(w) @ G))
%timeit L2 = np.sum(np.abs((w * G) @ G))              # <- more concise
%timeit L3 = np.linalg.norm(((w * G) @ G).ravel(), 1) # <- faster

[[0.93031972]
 [0.93031972]
 [0.93031972]]
8.54 µs ± 65.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
6.5 µs ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
6.45 µs ± 32.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
# nonlinear transform - 1-norm - diagonal - gradient

D1 = np.diag(G @ np.sign(G @ np.diag(w) @ G) @ G)
D2 = np.sum((G @ np.sign((w * G) @ G)) * G, axis=1)
D3 = np.sum(G * (np.sign((w * G) @ G) @ G), axis=0)
print(np.stack((D1, D2, D3)))

%timeit D1 = np.diag(G @ np.sign(G @ np.diag(w) @ G) @ G)
%timeit D2 = np.sum((G @ np.sign((w * G) @ G)) * G, axis=1)   # <- same speed
%timeit D3 = np.sum(G * (np.sign((w * G) @ G) @ G), axis=0)   # <- same speed



[[0.26373642 1.32560084 0.07636305 0.16162121 0.04822988 0.26049764
  0.69594308 1.14880557]
 [0.26373642 1.32560084 0.07636305 0.16162121 0.04822988 0.26049764
  0.69594308 1.14880557]
 [0.26373642 1.32560084 0.07636305 0.16162121 0.04822988 0.26049764
  0.69594308 1.14880557]]
9.04 µs ± 70 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
8.13 µs ± 43.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
8.15 µs ± 70.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
# nonlinear transform - 1-norm - non-convex - loss

L1 = np.sum(np.abs(W @ G @ W.T))
L2 = np.linalg.norm((W @ G @ W.T).ravel(), 1)
print(np.array([L1, L2]).reshape((-1, 1)))

%timeit L1 = np.sum(np.abs(W @ G @ W.T))              # <- more concise
%timeit L2 = np.linalg.norm((W @ G @ W.T).ravel(), 1) # <- faster

[[1.07656556]
 [1.07656556]]
6.6 µs ± 90.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
6.65 µs ± 55.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
# nonlinear transform - 1-norm - non-convex - gradient

%timeit D1 = np.sign(W @ G @ W.T) @ W @ G

5.24 µs ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
%%timeit
# linear transform - 2-norm - full matrix

L = .5 * np.dot(W.ravel(), W.ravel())
D = W

1.05 µs ± 3.69 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%%timeit
# linear transform - 2-norm - diagonal

L = .5 * np.dot(w, w)
D = w

876 ns ± 2.82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [34]:
%%timeit
# linear transform - 1-norm - full matrix

L = np.linalg.norm(W.ravel(), 1)
D = np.sign(W)

3.14 µs ± 49.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
%%timeit
# linear transform - 1-norm - diagonal

L = np.linalg.norm(w, 1)
D = np.sign(w)

2.97 µs ± 56.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
%%timeit
# nonlinear transform - 2-norm - full matrix

A = W @ G
L = .5 * np.dot(A.ravel(), A.T.ravel())
D = G @ A

4.62 µs ± 41.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
%%timeit
# nonlinear transform - 2-norm - diagonal

A = np.square(G)
L = .5 * np.dot(np.outer(w, w).ravel(), A.ravel())
D = A @ w

6.22 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
%%timeit
# nonlinear transform - 1-norm - full matrix

A = G @ W @ G
L = np.linalg.norm(A.ravel(), 1)
D = G @ np.sign(A) @ G

9.22 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%%timeit
# nonlinear transform - 1-norm - diagonal

A = (w * G) @ G
L = np.linalg.norm(A.ravel(), 1)
D = np.sum(G @ np.sign(A) * G, axis=1)

13 µs ± 686 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
%%timeit
# nonlinear transform - 1-norm - non-convex

A = W @ G @ W.T
L = np.linalg.norm(A.ravel(), 1)
D = np.sign(A) @ W @ G

9.47 µs ± 18.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [41]:
A = np.arange(4).reshape(2,2)
B = np.outer(A.ravel(), A.ravel()).reshape(2,2,2,2)
A[1,1] * A[1,0], B[1,1,1,0]

A = np.arange(8).reshape(4,2)
B = np.arange(4).reshape(2,2)
B = B + B.T
C = A @ B @ A.T
E = np.zeros((16,4))
E[0,:] = np.outer(A[0,:],A[0,:]).ravel()
E[1,:] = np.outer(A[0,:],A[1,:]).ravel()
E[2,:] = np.outer(A[0,:],A[2,:]).ravel()
E[3,:] = np.outer(A[0,:],A[3,:]).ravel()
E[4,:] = np.outer(A[1,:],A[0,:]).ravel()
E[5,:] = np.outer(A[1,:],A[1,:]).ravel()
E[6,:] = np.outer(A[1,:],A[2,:]).ravel()
E[7,:] = np.outer(A[1,:],A[3,:]).ravel()
E[8,:] = np.outer(A[2,:],A[0,:]).ravel()
E[9,:] = np.outer(A[2,:],A[1,:]).ravel()
E[10,:] = np.outer(A[2,:],A[2,:]).ravel()
E[11,:] = np.outer(A[2,:],A[3,:]).ravel()
E[12,:] = np.outer(A[3,:],A[0,:]).ravel()
E[13,:] = np.outer(A[3,:],A[1,:]).ravel()
E[14,:] = np.outer(A[3,:],A[2,:]).ravel()
E[15,:] = np.outer(A[3,:],A[3,:]).ravel()
D = (np.dot(A.reshape(4,2,1), A.reshape(4,1,2)).transpose(0,2,1,3).reshape(16,4) @ B.reshape(4,1)).reshape(4,4)
F = (E @ B.reshape(4,1)).reshape(4,4)
C, np.int_(D), np.int_(F)
C, A[0:2,np.repeat(np.arange(2),2)] * A[0:2,np.tile(np.arange(2),2)] @ B.reshape(4,1)
#C, (np.dot(A[[0, 2], :].reshape(2,2,1), A[[0, 1, 3], :].reshape(3,1,2)).transpose(0,2,1,3).reshape(6,4) @ B.reshape(4,1)).reshape(2,3)



(array([[  6,  24,  42,  60],
        [ 24,  90, 156, 222],
        [ 42, 156, 270, 384],
        [ 60, 222, 384, 546]]),
 array([[ 6],
        [90]]))

In [26]:
n = 7
d = 4
r = np.array([0, 2])
c = np.array([0, 2, 3])

A = np.int_(np.arange(n * d).reshape(n, d) ** (8 / 7))
B = np.arange(d ** 2).reshape(d, d)
B = B + B.T + 1
print(A)
print(B)

P = A @ B @ A.T
D = P.diagonal()[:, None]
R = D + D.T - 2 * P
R1 = R[r][:, c]
print(R)
print(R1)

R2 = (A[r][:, np.repeat(np.arange(d), d)] * A[r][:, np.tile(np.arange(d), d)] @ B.reshape(d ** 2, 1) +
      (A[c][:, np.repeat(np.arange(d), d)] * A[c][:, np.tile(np.arange(d), d)] @ B.reshape(d ** 2, 1)).T -
      2 * A[r] @ B @ A[c].T
     )
print(R2)

R3 = (A[r][:, np.repeat(np.arange(d), d)] * A[r][:, np.tile(np.arange(d), d)] @ B.reshape(d ** 2, 1) +
      (A[c][:, np.repeat(np.arange(d), d)] * A[c][:, np.tile(np.arange(d), d)] @ B.reshape(d ** 2, 1)).T -
      2 * (np.dot(A[r].reshape(r.size, d , 1),
                  A[c].reshape(c.size, 1 , d)).transpose(0,2,1,3).reshape(r.size * c.size, d ** 2)
           @ B.reshape(d ** 2, 1)).reshape(r.size, c.size)
     )
print(R3)

[[ 0  1  2  3]
 [ 4  6  7  9]
 [10 12 13 15]
 [17 18 20 22]
 [23 25 27 28]
 [30 32 34 35]
 [37 39 41 43]]
[[ 1  6 11 16]
 [ 6 11 16 21]
 [11 16 21 26]
 [16 21 26 31]]
[[     0   7000  32296  83141 153939 254375 387156]
 [  7000      0   9216  41871  95249 176925 289976]
 [ 32296   9216      0  11799  45209 105381 195800]
 [ 83141  41871  11799      0  10816  46656 111469]
 [153939  95249  45209  10816      0  12544  52839]
 [254375 176925 105381  46656  12544      0  13891]
 [387156 289976 195800 111469  52839  13891      0]]
[[    0 32296 83141]
 [32296     0 11799]]
[[    0 32296 83141]
 [32296     0 11799]]
[[    0 32296 83141]
 [32296     0 11799]]


In [37]:
n = 7
d = 4
r = np.array([0, 2])
c = np.array([0, 2, 3])

A = np.int_(np.arange(n * d).reshape(n, d) ** (8 / 7))
B = np.arange(n ** 2).reshape(n, n)
print(A)
print(B)

R1 = np.zeros((d, d), dtype=int)
for i in range(n):
    for j in range(n):
        C = A[i] - A[j]
        R1 += B[i, j] * np.outer(C, C)
print(R1)

C = A.reshape(n, 1, d) - A.reshape(1, n, d)
R2 = np.tensordot(B, C.reshape(n, n, d, 1) @ C.reshape(n, n, 1, d))
print(R2)

C = B + B.T
R3 = A.T @ (np.diag(np.sum(C, axis=0)) - C) @ A
print(R3)

[[ 0  1  2  3]
 [ 4  6  7  9]
 [10 12 13 15]
 [17 18 20 22]
 [23 25 27 28]
 [30 32 34 35]
 [37 39 41 43]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
[[385728 391544 403688 402880]
 [391544 397768 409960 409104]
 [403688 409960 422680 421704]
 [402880 409104 421704 421304]]
[[385728 391544 403688 402880]
 [391544 397768 409960 409104]
 [403688 409960 422680 421704]
 [402880 409104 421704 421304]]
[[385728 391544 403688 402880]
 [391544 397768 409960 409104]
 [403688 409960 422680 421704]
 [402880 409104 421704 421304]]


In [122]:
I = np.array([True, False, False, True, False])
A = np.random.randint(0,10,(5,5)) - 4.5
A = A + A.T
B = np.random.randint(0,10,(5,5)) - 4.5
B = B + B.T
V = np.random.randint(0,10,(5,5)) - 4.5
V[~I, :] = 0
V[:, ~I] = 0
U = np.diag(np.sum(V + V.T, axis=0)) - (V + V.T)

a = .1

R1 = .5 * np.trace(A @ B @ A @ B)
R2 = .5 * np.dot((A @ B).T.ravel(), (A @ B).ravel())

print(R1, R2)

M = A + a * A + U

F1 = .5 * np.trace(M @ B @ M @ B)
F2 = .5 * np.dot((M @ B).T.ravel(), (M @ B).ravel())

print(F1, F2)

C1 = (1 + a) ** 2 * R1 + (1 + a) * np.trace(A @ B @ U @ B) + .5 * np.trace(U @ B @ U @ B)
C2 = (1 + a) ** 2 * R2 + (1 + a) * np.dot((A @ B).T.ravel(), (U @ B).ravel()) + .5 * np.dot((U @ B).T.ravel(), (U @ B).ravel())

print(C1, C2)

D1 = ((1 + a) ** 2 * R2 +
     (1 + a) * np.dot((A @ B[:, I]).T.ravel(), (U[I, :][:, I] @ B[I, :]).ravel()) +
     .5 * np.dot((U[I, :][:, I] @ B[I, :][:, I]).T.ravel(), (U[I, :][:, I] @ B[I, :][:, I]).ravel()))

BS = B[I]
CS = A @ BS.T
US = U[I, :][:, I]
UB = US @ BS

D2 = ((1 + a) ** 2 * R2 +
      (1 + a) * np.dot(CS.T.ravel(), UB.ravel()) +
      .5 * np.dot(UB[:, I].T.ravel(), UB[:, I].ravel()))

J = np.nonzero(I)[0]
BS = B.take(J, axis=0)
CS = A @ BS.T
US = U.take(J, axis=0).take(J, axis=1)
UB = US @ BS

D3 = ((1 + a) ** 2 * R2 +
      (1 + a) * np.dot(CS.T.ravel(), UB.ravel()) +
      .5 * np.dot(UB.take(J, axis=1).T.ravel(), UB.take(J, axis=1).ravel()))

print(D1, D2, D3)


12157.5 12157.5
23273.375 23273.375
23273.375000000004 23273.375000000004
23273.375000000004 23273.375000000004 23273.375000000004
