In [1]:
import numpy as np
rng = np.random.Generator(np.random.PCG64(12345))
m = 3
n = 5
B1 = rng.standard_normal(n * m).reshape(n, m)
B2 = B1 @ B1.T
C = B2
B1, B2

(array([[-1.42382504,  1.26372846, -0.87066174],
        [-0.25917323, -0.07534331, -0.74088465],
        [-1.3677927 ,  0.6488928 ,  0.36105811],
        [-1.95286306,  2.34740965,  0.96849691],
        [-0.75938718,  0.90219827, -0.46695317]]),
 array([[ 4.38233921,  0.91886378,  2.45316231,  4.90379051,  2.62792638],
        [ 0.91886378,  0.62175745,  0.03810312, -0.38827626,  0.47479667],
        [ 2.45316231,  0.03810312,  2.4222817 ,  4.54401274,  1.45551698],
        [ 4.90379051, -0.38827626,  4.54401274, 10.26199248,  3.14856541],
        [ 2.62792638,  0.47479667,  1.45551698,  3.14856541,  1.60867588]]))

In [ ]:
A1 = rng.standard_normal(m * m).reshape(m, m) / m ** .5
A1 = A1.T @ A1
A2 = rng.standard_normal(n * n).reshape(n, n) / n ** .5
A2 = A2.T @ A2
K = A1; A1 /= np.dot(K.T.ravel(), K.ravel()) ** .5
K = A2 @ C; A2 /= np.dot(K.T.ravel(), K.ravel()) ** .5
A1, A2, .5 * np.dot(A1.ravel(), A1.T.ravel()), .5 * np.dot((A2 @ C).ravel(), (A2 @ C).T.ravel())

(array([[0.23337542, 0.41369941],
        [0.41369941, 0.77668624]]),
 array([[ 0.14289542,  0.01002172,  0.07014635, -0.07912996, -0.11563492],
        [ 0.01002172,  0.17579574, -0.26088536,  0.04038172,  0.06953828],
        [ 0.07014635, -0.26088536,  0.56525092, -0.01664508, -0.20897969],
        [-0.07912996,  0.04038172, -0.01664508,  0.15500317,  0.09168808],
        [-0.11563492,  0.06953828, -0.20897969,  0.09168808,  0.1695301 ]]),
 0.49999999999999994,
 0.4999999999999999)

In [ ]:
A1 = np.diag(np.ones(m) / m ** .5)
A2 = np.diag(np.ones(n) / n ** .5)
K = A1; A1 /= np.dot(K.T.ravel(), K.ravel()) ** .5
K = A2 @ C; A2 /= np.dot(K.T.ravel(), K.ravel()) ** .5
A1, A2, .5 * np.dot(A1.ravel(), A1.T.ravel()), .5 * np.dot((A2 @ C).ravel(), (A2 @ C).T.ravel())

(array([[0.70710678, 0.        ],
        [0.        , 0.70710678]]),
 array([[0.10918022, 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.10918022, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.10918022, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.10918022, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.10918022]]),
 0.5000000000000001,
 0.4999999999999999)

In [ ]:
U = np.identity(n) - 1 / n
A1 = B1.T @ U @ B1
A1 = (A1 + A1.T) / 2
A2 = B2.T @ U @ B2
A2 = (A2 + A2.T) / 2
K = A1; A1 /= np.dot(K.T.ravel(), K.ravel()) ** .5
K = A2 @ C; A2 /= np.dot(K.T.ravel(), K.ravel()) ** .5
A1, A2, .5 * np.dot(A1.ravel(), A1.T.ravel()), .5 * np.dot((A2 @ C).ravel(), (A2 @ C).T.ravel())
A1.sum(axis=0), A1.sum(axis=1), A2.sum(axis=0), A2.sum(axis=1)

(array([-0.15102024,  0.28071322]),
 array([-0.15102024,  0.28071322]),
 array([ 0.02174263,  0.00340885, -0.00658832,  0.01547291, -0.0211531 ]),
 array([ 0.02174263,  0.00340885, -0.00658832,  0.01547291, -0.0211531 ]))

In [ ]:
U = np.identity(n) - 1 / n
A1 = B1.T @ U @ B1
A1 = (A1 + A1.T) / 2
A2 = B2.T @ U @ B2
A2 = (A2 + A2.T) / 2

A1 -= np.sum(A1, axis=0, keepdims=True) / m
A1 -= np.sum(A1, axis=1, keepdims=True) / m
A2 -= np.sum(A2, axis=0, keepdims=True) / n
A2 -= np.sum(A2, axis=1, keepdims=True) / n

A1 - A1.T, A2 - A2.T

(array([[0., 0.],
        [0., 0.]]),
 array([[ 0.00000000e+00, -8.88178420e-16,  1.77635684e-15,
          1.77635684e-15,  0.00000000e+00],
        [ 8.88178420e-16,  0.00000000e+00,  3.33066907e-16,
          0.00000000e+00,  4.44089210e-16],
        [-1.77635684e-15, -3.33066907e-16,  0.00000000e+00,
         -1.77635684e-15,  0.00000000e+00],
        [-1.77635684e-15,  0.00000000e+00,  1.77635684e-15,
          0.00000000e+00, -3.55271368e-15],
        [ 0.00000000e+00, -4.44089210e-16,  0.00000000e+00,
          3.55271368e-15,  0.00000000e+00]]))

In [ ]:
H1 = np.identity(m) - 1 / m
H2 = np.identity(n) - 1 / n
A1 = H1 @ B1.T @ H2 @ B1 @ H1
A2 = H2 @ B2.T @ H2 @ B2 @ H2
K = A1; A1 /= np.dot(K.T.ravel(), K.ravel()) ** .5
K = A2 @ C; A2 /= np.dot(K.T.ravel(), K.ravel()) ** .5
A1, A2, .5 * np.dot(A1.ravel(), A1.T.ravel()), .5 * np.dot((A2 @ C).ravel(), (A2 @ C).T.ravel())
A1.sum(axis=0), A1.sum(axis=1), A2.sum(axis=0), A2.sum(axis=1)

(array([0., 0.]),
 array([0., 0.]),
 array([ 0.00000000e+00,  8.67361738e-19,  1.04083409e-17,  6.93889390e-18,
        -1.38777878e-17]),
 array([1.38777878e-17, 0.00000000e+00, 0.00000000e+00, 3.46944695e-18,
        0.00000000e+00]))

In [ ]:
(U @ B1).sum(axis=0), (U @ B1).sum(axis=1)

(array([0.00000000e+00, 2.22044605e-16]),
 array([ 0.72327629, -0.2464621 ,  0.06714491,  0.16447297, -0.70843208]))

In [ ]:
A1 = rng.standard_normal(m * m).reshape(m, m) / m ** .5
A2 = rng.standard_normal(m * n).reshape(m, n) / m ** .5
K = A1 @ A1.T; A1 /= np.dot(K.T.ravel(), K.ravel()) ** .25
K = A2 @ C @ A2.T; A2 /= np.dot(K.T.ravel(), K.ravel()) ** .25

.5 * np.dot((A1 @ A1.T).ravel(), (A1 @ A1.T).T.ravel()), .5 * np.dot((A2 @ C @ A2.T).ravel(), (A2 @ C @ A2.T).T.ravel())

(0.4999999999999999, 0.5000000000000001)

In [ ]:
A1 -= np.sum(A1, axis=1, keepdims=True) / m
A2 -= np.sum(A2, axis=1, keepdims=True) / n
(A1.T @ A1).sum(axis=0), (A1.T @ A1).sum(axis=1), (A2.T @ A2).sum(axis=0), (A2.T @ A2).sum(axis=1)

(array([-2.08166817e-17, -2.77555756e-17, -6.93889390e-18]),
 array([-2.08166817e-17, -2.77555756e-17, -6.93889390e-18]),
 array([-1.04083409e-17,  3.25260652e-18, -6.93889390e-18,  1.04083409e-17,
         0.00000000e+00]),
 array([-1.04083409e-17,  3.25260652e-18, -6.93889390e-18,  1.04083409e-17,
         0.00000000e+00]))

In [ ]:
A = np.random.randn(5, 5)
A = A.T @ A
B = np.ones(5).reshape(5, 1)
B = B.ravel()

eigenvalues, eigenvectors = np.linalg.eigh(A)
eigenvalues.shape, B.shape

((5,), (5,))

In [ ]:
A = np.array([2, 1, 5, 3, 4]).reshape(5, 1)
B = A.ravel()
I = np.identity(5)
O = np.flip(np.argsort(B))
B = B[O]
I = I[:, O]
A, B, O, I

(array([[2],
        [1],
        [5],
        [3],
        [4]]),
 array([5, 4, 3, 2, 1]),
 array([2, 4, 3, 0, 1]),
 array([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]]))

In [ ]:
A = np.array([2, 1, 5, 3, 4]).reshape(5, 1).flatten()
I = np.identity(5)
O = np.argsort(A)
A = A[O]
I = I[:, O]
W = I[:, 3:] @ np.diag(A[3:]) @ I[:, 3:].T
S, V = np.linalg.eigh(W)
i = np.argmax(S > 0)
D = V[:, i:]
E = V[:, 5-3:]
A, I, W, S, V, i, D, E, A > 3

(array([1, 2, 3, 4, 5]),
 array([[0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 4.]]),
 array([0., 0., 0., 4., 5.]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]]),
 3,
 array([[0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [1., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([False, False, False,  True,  True]))

In [ ]:
m = 3
n = 5
A = rng.standard_normal((m, n))
B = rng.standard_normal((m, n))
C = np.sum(A * B, axis=1, keepdims=True)
D = np.einsum('ij, ij->i', A, B)
A, B, C, D

(array([[-0.81188688, -0.02553817,  1.15818454,  0.30052087,  0.05305665],
        [ 0.25727152,  0.03574286,  0.54723669, -1.12296158, -1.97524767],
        [-0.42515005, -1.14907382,  1.61513805, -0.15847686, -0.25287335]]),
 array([[-1.53815403,  0.28208603, -0.62361213,  1.12182226,  0.84122103],
        [-0.7758961 ,  0.41071644, -2.7224161 , -0.6733048 ,  1.24622153],
        [ 0.79020803,  0.17534089, -0.0292946 , -1.41951426, -1.35996632]]),
 array([[ 0.90110855],
        [-3.38024251],
        [-0.01589204]]),
 array([ 0.90110855, -3.38024251, -0.01589204]))

self.O = np.sum(self.Q * self.inner_loss.func(self.I), axis=1, keepdims=True)
self.dRdA = self.r * np.sum(self.C * self.K, axis=1, keepdims=True)
self.dLdA = self.l * np.sum(B.T * (Y @ B).T, axis=1, keepdims=True)

P = self.B @ self.A @ self.B.T

self.B @ (self.D * self.B.T)

U = self.A @ self.B.T
P = U.T @ U

self.dLdA = self.l * (B.T @ Y @ B)

self.dLdA = self.l * np.sum(B.T * (Y @ B).T, axis=1, keepdims=True)

self.dLdA = self.l * 2 * ((self.A @ B.T) @ Y @ B)

self.B.T @ (np.identity(self.n) - 1 / self.n) @ self.B

K = A @ self.C @ A.T

In [ ]:
import numpy as np
rng = np.random.Generator(np.random.PCG64(12345))

n = 5
m = 3
d = 2

Q = rng.standard_normal((n, n))
I = rng.standard_normal((n, n))
C = rng.standard_normal((m, m))
K = rng.standard_normal((m, m))
A = rng.standard_normal((m, m))
Y = rng.standard_normal((n, n))
B = rng.standard_normal((n, m))
D = rng.standard_normal((m, 1))
E = rng.standard_normal((d, m))

O1 = np.sum(Q * I, axis=1, keepdims=True)
O2 = np.einsum('ij,ij->i', Q, I).reshape(-1, 1)
R1 = np.sum(C * K, axis=1, keepdims=True)
R2 = np.einsum('ij,ij->i', C, K).reshape(-1, 1)
N1 = np.sum(E * E, axis=1, keepdims=True)
N2 = np.einsum('ij,ij->i', E, E).reshape(-1, 1)
L1 = np.sum(B.T * (Y @ B).T, axis=1, keepdims=True)
L2 = np.einsum('ij,ij->j', B, Y @ B).reshape(-1, 1)
L3 = np.einsum('ij,ik,kj->j', B, Y, B).reshape(-1, 1)

P1 = B @ A @ B.T
P2 = np.einsum('ij,jk,lk->il', B, A, B)

W1 = B @ (D * B.T)
W2 = np.einsum('ij,j,kj->ik', B, D.ravel(), B)

U = A @ B.T; S1 = U.T @ U
S2 = np.einsum('ij,kj,kl,ml->im', B, A, A, B)

X1 = B.T @ Y @ B
X2 = np.einsum('ji,jk,kl->il', B, Y, B)

Z1 = (E @ B.T) @ Y @ B
Z2 = np.einsum('ij,kj,kl,lm->im', E, B, Y, B)

M1 = A @ C @ A.T
M2 = np.einsum('ij,jk,lk->il', A, C, A)

O1, O2, R1, R2, N1, N2, L1, L2, L3, P1, P2, W1, W2, S1, S2, X1, X2, Z1, Z2, M1, M2

(array([[-2.91107835],
        [-0.01026069],
        [ 1.27096151],
        [-1.86420414],
        [-0.40020136]]),
 array([[-2.91107835],
        [-0.01026069],
        [ 1.27096151],
        [-1.86420414],
        [-0.40020136]]),
 array([[-0.31551936],
        [ 1.1419231 ],
        [-1.66834164]]),
 array([[-0.31551936],
        [ 1.1419231 ],
        [-1.66834164]]),
 array([[2.00120394],
        [0.15931644]]),
 array([[2.00120394],
        [0.15931644]]),
 array([[-1.10292925],
        [-3.08800613],
        [ 0.12001286]]),
 array([[-1.10292925],
        [-3.08800613],
        [ 0.12001286]]),
 array([[-1.10292925],
        [-3.08800613],
        [ 0.12001286]]),
 array([[ 0.36919543,  1.9758966 ,  0.17268966, -1.66166938,  0.21372156],
        [ 2.0859279 ,  5.49755614,  3.91354428, -1.51074717,  5.34832522],
        [-1.15733626,  4.64508597,  4.76758993, -0.43786416,  2.73665568],
        [-2.91217265, -0.89589239,  0.44390757,  0.80796119, -2.65456801],
        [-1.1861261

In [ ]:
import numpy as np
rng = np.random.Generator(np.random.PCG64(12345))

n = 15000
m = 150
d = 15

Q = rng.standard_normal((n, n))
I = rng.standard_normal((n, n))
C = rng.standard_normal((m, m))
K = rng.standard_normal((m, m))
A = rng.standard_normal((m, m))
Y = rng.standard_normal((n, n))
B = rng.standard_normal((n, m))
D = rng.standard_normal((m, 1))
E = rng.standard_normal((d, m))


O2_path = np.einsum_path('ij,ij->i', Q, I, optimize='optimal')
R2_path = np.einsum_path('ij,ij->i', C, K, optimize='optimal')
N2_path = np.einsum_path('ij,ij->i', E, E, optimize='optimal')
L2_path = np.einsum_path('ij,ij->j', B, Y @ B, optimize='optimal')
L3_path = np.einsum_path('ij,ik,kj->j', B, Y, B, optimize='optimal')
P2_path = np.einsum_path('ij,jk,lk->il', B, A, B, optimize='optimal')
W2_path = np.einsum_path('ij,j,kj->ik', B, D.ravel(), B, optimize='optimal')
S2_path = np.einsum_path('ij,kj,kl,ml->im', B, A, A, B, optimize='optimal')
X2_path = np.einsum_path('ji,jk,kl->il', B, Y, B, optimize='optimal')
Z2_path = np.einsum_path('ij,kj,kl,lm->im', E, B, Y, B, optimize='optimal')
M2_path = np.einsum_path('ij,jk,lk->il', A, C, A, optimize='optimal')

In [ ]:
print(O2_path[1])
print(R2_path[1])
print(N2_path[1])
print(L2_path[1])
print(L3_path[1])
print(P2_path[1])
print(W2_path[1])
print(S2_path[1])
print(X2_path[1])
print(Z2_path[1])
print(M2_path[1])

  Complete contraction:  ij,ij->i
         Naive scaling:  2
     Optimized scaling:  2
      Naive FLOP count:  4.500e+08
  Optimized FLOP count:  4.500e+08
   Theoretical speedup:  1.000
  Largest intermediate:  1.500e+04 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   2                    ij,ij->i                                     i->i
  Complete contraction:  ij,ij->i
         Naive scaling:  2
     Optimized scaling:  2
      Naive FLOP count:  4.500e+04
  Optimized FLOP count:  4.500e+04
   Theoretical speedup:  1.000
  Largest intermediate:  1.500e+02 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   2        

In [ ]:
%timeit O1 = np.sum(Q * I, axis=1, keepdims=True)
%timeit O2 = np.einsum('ij,ij->i', Q, I, optimize=O2_path[0]).reshape(-1, 1)

946 ms ± 31.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
337 ms ± 25.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit R1 = np.sum(C * K, axis=1, keepdims=True)
%timeit R2 = np.einsum('ij,ij->i', C, K, optimize=R2_path[0]).reshape(-1, 1)

35.4 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
49.4 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit N1 = np.sum(E * E, axis=1, keepdims=True)
%timeit N2 = np.einsum('ij,ij->i', E, E, optimize=N2_path[0]).reshape(-1, 1)

10.6 µs ± 2.16 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
38.8 µs ± 3.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit L1 = np.sum(B.T * (Y @ B).T, axis=1, keepdims=True)
%timeit L2 = np.einsum('ij,ij->j', B, Y @ B, optimize=L2_path[0]).reshape(-1, 1)
%timeit L3 = np.einsum('ij,ik,kj->j', B, Y, B, optimize=L3_path[0]).reshape(-1, 1)

3.04 s ± 645 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.94 s ± 486 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.01 s ± 403 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit P1 = B @ A @ B.T
%timeit P2 = np.einsum('ij,jk,lk->il', B, A, B, optimize=P2_path[0])

2.72 s ± 403 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3 s ± 447 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit W1 = B @ (D * B.T)
%timeit W2 = np.einsum('ij,j,kj->ik', B, D.ravel(), B, optimize=W2_path[0])

2.69 s ± 288 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.94 s ± 437 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit U = A @ B.T; S1 = U.T @ U
%timeit S2 = np.einsum('ij,kj,kl,ml->im', B, A, A, B, optimize=S2_path[0])

3.27 s ± 294 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.2 s ± 555 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit X1 = B.T @ Y @ B
%timeit X2 = np.einsum('ji,jk,kl->il', B, Y, B, optimize=X2_path[0])

2.95 s ± 469 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.03 s ± 563 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit Z1 = (E @ B.T) @ Y @ B
%timeit Z2 = np.einsum('ij,kj,kl,lm->im', E, B, Y, B, optimize=Z2_path[0])

979 ms ± 190 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
806 ms ± 17.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit M1 = A @ C @ A.T
%timeit M2 = np.einsum('ij,jk,lk->il', A, C, A, optimize=M2_path[0])

887 µs ± 335 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
889 µs ± 13.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
A = rng.standard_normal((2, 5))
B = rng.standard_normal((2, 5))
C = np.sign(np.sum(A * B, axis=1, keepdims=True))
D = A.copy()
D *= np.sign(np.sum(D * B, axis=1, keepdims=True))
A, B, C, D


(array([[ 0.27795728,  0.50628278,  1.40121131, -0.47365369,  0.58637786],
        [-1.61190757,  0.80620584, -0.14786626, -1.60869104, -1.04487596]]),
 array([[ 0.9544797 , -0.1138387 ,  1.46620828,  0.32658842,  1.78452265],
        [ 0.9853827 ,  0.7466556 ,  1.83278257,  0.99720804,  0.13485569]]),
 array([[ 1.],
        [-1.]]),
 array([[ 0.27795728,  0.50628278,  1.40121131, -0.47365369,  0.58637786],
        [ 1.61190757, -0.80620584,  0.14786626,  1.60869104,  1.04487596]]))

In [ ]:
A = np.arange(4).reshape(2, 2)
A, np.where(A == 0, 1, A)

(array([[0, 1],
        [2, 3]]),
 array([[1, 1],
        [2, 3]]))

In [3]:
np.array_equal(B1, B2)

False